---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redlib
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redlib-secret
    template:
      engineVersion: v2
      data:
        REDLIB_DEFAULT_SUBSCRIPTIONS: "{{ .REDLIB_DEFAULT_SUBSCRIPTIONS }}"
  dataFrom:
    - extract:
        key: redlib
