---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink
spec:
  refreshInterval: 5m
  target:
    name: shlink-secret
    creationPolicy: Owner
    template:
      data:
        DB_HOST: '{{ index . "host" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'

        GEOLITE_LICENSE_KEY: "{{ .GEOLITE_LICENSE_KEY }}"
        SHLINK_SERVER_NAME: "opstimus"
        SHLINK_SERVER_API_KEY: &apikey "{{ .SHLINK_API_KEY }}"
        INITIAL_API_KEY: *apikey
  dataFrom:
    - extract:
        key: geolite
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: shlink
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-shlink
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
