---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  target:
    name: miniflux-secret
    template:
      data:
        # user
        ADMIN_USERNAME: "{{ .MNFX_ADMIN_USER }}"
        ADMIN_PASSWORD: "{{ .MNFX_ADMIN_PASS }}"
        # OIDC
        OAUTH2_OIDC_PROVIDER_NAME: authentik
        OAUTH2_CLIENT_ID: "{{ .MNFX_AK_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .MNFX_AK_CLIENT_SECRET }}"
        # Database
        DATABASE_URL: 'host={{ index . "pgbouncer-host" }} port={{ index . "pgbouncer-port" }} user={{ .user }} password={{ .password }} dbname={{ .dbname }}'
  dataFrom:
    - extract:
        key: miniflux
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-miniflux
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
