---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homebox
spec:
  refreshInterval: 5m
  target:
    name: homebox-secret
    creationPolicy: Owner
    template:
      data:
        # mail
        HBOX_MAILER_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        HBOX_MAILER_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        HBOX_MAILER_USERNAME: "{{ .EXTERNAL_SMTP_USER }}"
        HBOX_MAILER_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        HBOX_MAILER_FROM: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
        # db
        HBOX_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        HBOX_DATABASE_PORT: '{{ index . "pgbouncer-port" }}'
        HBOX_DATABASE_USERNAME: '{{ index . "user" }}'
        HBOX_DATABASE_PASSWORD: '{{ index . "password" }}'
        HBOX_DATABASE_DATABASE: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: external-smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-homebox
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
