---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gramps
spec:
  target:
    name: gramps-secret
    template:
      data:
        GRAMPSWEB_SECRET_KEY: "{{ .GRAMPS_SECRET_KEY }}"
        GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://{{ .DF_HOST }}:{{ .DF_REDIS_PORT }}/{{ .DF_REDIS_GRAMPS_DB }}"
        GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://{{ .DF_HOST }}:{{ .DF_REDIS_PORT }}/{{ .DF_REDIS_GRAMPS_DB }}"
        GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://{{ .DF_HOST }}:{{ .DF_REDIS_PORT }}/{{ .DF_REDIS_GRAMPS_RL_DB }}"
        # db
        POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "port" }}'
        GRAMPSWEB_POSTGRES_USER: '{{ index . "user" }}'
        GRAMPSWEB_POSTGRES_PASSWORD: '{{ index . "password" }}'
        GRAMPSWEB_USER_DB_URI: 'postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "pgbouncer-host" }}:{{ index . "port" }}/gramps_users'
        GRAMPSWEB_SEARCH_INDEX_DB_URI: 'postgresql://{{ index . "user" }}:{{ index . "password" }}@{{ index . "pgbouncer-host" }}:{{ index . "port" }}/gramps_search'
        # email
        GRAMPSWEB_EMAIL_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        GRAMPSWEB_EMAIL_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        GRAMPSWEB_EMAIL_HOST_USER: "{{ .EXTERNAL_SMTP_USER }}"
        GRAMPSWEB_EMAIL_HOST_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        GRAMPSWEB_DEFAULT_FROM_EMAIL: "Gramps <{{ .EXTERNAL_SMTP_FROM_EMAIL }}>"
  dataFrom:
    - extract:
        key: dragonfly
      sourceRef: &onepass
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: gramps
      sourceRef: *onepass
    - extract:
        key: external-smtp
      sourceRef: *onepass
    - extract:
        key: crunchy-postgres-pguser-gramps
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
