# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:V70XJQ99erNRe/3S5Kfb9jF/REBZM7tROK/IGNTba+i1yYQ1SFsYeQqKlkCgE2YKqEKplDyiUDVvDiaCGik3eqO76+VBH918mUhTZlLFzm0v3LElLLYNwEvuNb02ca/N8wVNLTIPho2HLSGIg6DkDHibxihn+EW9bcnQxl9YbrEsX9RulOVMNcEezelBnRQnO7dIvAzeK2myT04joCo1oKKXYw4KkaaQjnmKy+YJXCZFoPgZnA==,iv:uWFC1CRKm9VYpW20Bw0Qw8t8pWKfsSgSAxfEIX6Eqc0=,tag:SXoK05PE3q9tpyn43eYnKQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWnh5ZEVRM3AveW9uYmtR
        dWV6bU9tVjBJR0RnWEx6N2YrZHRJdWF4MzNJCmVSWXM5aUU1UXAvRFlNUndtejRi
        YUQ2dUxZSVNmWGluUzIzVlpGdHh3YU0KLS0tIGIvaTRDd252UWhER0VRM1RXVmtZ
        aHJoSm9ZKzFHa0k5YTFmV2Y3Z0srRWcKPgt4Jd5KrthxD7AUvEck1KjoQLUpJ5/6
        sVLGuS+PTrjrJYjfqwvf/uMZ4Vl9n/pj2G3jjAxc/2Ygc4nTs10HxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:08:31Z"
  mac: ENC[AES256_GCM,data:9RrDeh2t5IHOfAVvNqtEJd3NA8qT7XyTHRcFdImLl3+bx5SZb5/pOFeh1IkI7IPf76Qin+Z9/LJLLwVpRzoCJCHESbmnlUXZL16U/nqN0KLcaz0a/AiMZ/Eyh60nwi69G7BrPFX6VNBDVDehSbrESE4Pr0F93u/tIUdOC0wA+s0=,iv:wlDWGJGtoPWbrgCCpr6v5PEH/N3HlVMfJlPlXSx7rn4=,tag:yYMDu7HHElRKpuzPuVgt6A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
