# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RKYBAPO2p73Nl+Y1wivzD1A6lPVYPntpxUKerrRpEai2xCGtKf1i7p4MnNmcZ9ckNsdOKQ0k+e4HxRWJ6qYeJJsMK/3MTUIrXxIoW5H+V/UDHRxolwNJVjwUJlh1AfRYDcmhmTDUsSztFcrNiE3d1GISEPqIzttbvVGb9KZ5lOeOW7ORkh0SOuMwP8fPuMt1E/PQx8Yg4Ajb0pK7z54wz20Vuwn488xanFu4AsRsBk9IInHqpQ==,iv:uSwoQLPPiz8K2QaaSQy+3wKTxMHOSngDbdbsMq5TFQA=,tag:zQBDTe3sXG6A4365IAwytg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSUFYSXg5aEdyUEdJWkox
        R1VLV2JGY3BIakNheVNyYmpsS0pNQ0FZS3hvCmk5SC9wNXdLMlJYOUlueTNzam0r
        NUFNcm9HbnhhcGFzNUIvSjFWSEc1VTQKLS0tIC9ieDBZTUdxZHMwdWlBYlA2VE9G
        T1J2OTlEK2QrUzk4bzM3QUxmUkRTalkK02X3u+gV1GgQ+qLpOBL+6vpNIus4H+qJ
        1wkhBvs3XkPQTieb0mpIR+QtCJb5y1Kd0nHmmCKO1FJqE36UcfEXtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T20:48:33Z"
  mac: ENC[AES256_GCM,data:cSchCaa+zRbBWHSZP6NIZsPbQIK2sW6Ic4emayfUs1v81xlbMMvhXBeoBF65MN0aRB87G+KwvQf3fVTgVWCeOI0U1vtCEgpTc7NXr1xAXVwRxtfhpSXtWeASl2WRr/mEGzlSZIKL4BE/IWuB2IdAYL98eQ9sL7hzqKTGt3Iix9s=,iv:hi7NSKD+Mrd1qEX3H+kXPjs2Z2zXisK2kjWGwz26s8Y=,tag:3j48LiE926oUG8DNlYhHIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
