---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1003
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      syncthing:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          syncthing:
            image:
              repository: syncthing/syncthing
              tag: 1.29.5
            resources:
              requests:
                cpu: 15m
                memory: 64M
              limits:
                cpu: 2000m
                memory: 1G
    service:
      app:
        controller: syncthing
        ports:
          http:
            port: 8384

      listen:
        enabled: true
        type: LoadBalancer
        controller: syncthing
        annotations:
          lbipam.cilium.io/ips: ${CILIUM_SVC_SYNCTHING_ADDR}
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP
          listen-udp:
            enabled: true
            port: 22000
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: apps
          gethomepage.dev/name: syncthing
          gethomepage.dev/icon: sh-syncthing.svg
          gethomepage.dev/description: file sync
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /var/syncthing

      media-swap:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MOUNT_MEDIA_SWAP}
        globalMounts:
          - path: /mnt/mediaswap
