---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    controllers:
      syncthing:
        containers:
          app:
            image:
              repository: syncthing/syncthing
              tag: 2.0.7@sha256:9f78e172614132f96befeec5c857164222df0da99aaf7620355c2d5d8ce09dac
            env:
              PUID: "568"
              PGID: "568"
            securityContext:
              # allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: 249Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsGroup: 568
        runAsUser: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        # runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8384
      discovery:
        enabled: true
        controller: *app
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP
          listen-udp:
            enabled: true
            port: 22000
            protocol: UDP
    ingress:
      app:
        className: internal
        # annotations:
        #           gethomepage.dev/enabled: "true"
        #           gethomepage.dev/group: apps
        #           gethomepage.dev/name: syncthing
        #           gethomepage.dev/icon: sh-syncthing.svg
        #           gethomepage.dev/description: file sync
        # nginx.ingress.kubernetes.io/whitelist-source-range: |
        #   10.42.0.0/16,10.43.0.0/16,192.168.86.0/24
        hosts:
          - host: &host sync.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/syncthing
      files:
        type: nfs
        server: ${NAS_IP}
        path: "/mnt/datastore/mediacentre/music"
        globalMounts:
          - path: /media
            subPath: downloads
      emulation:
        type: nfs
        server: ${NAS_IP}
        path: /mnt/datastore/kubernetes/
        globalMounts:
          - path: /emulation/
            subPath: Library/Emulation/
