apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # Change to your namespace
  namespace: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:BIrTl06jYWa6ow==,iv:40aibIGc4CZettmnFdgkLzUK4vn7gungOptOY2faS+g=,tag:XRxqVtNzEn4WAM8PKdpetA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:TTP1NrMvsWT8lRcc,iv:RCkhwnxMqWhf0wkpNyYycAa6NxC9X6yFfy1NfX/fceo=,tag:WQcPYj9VPWrLJh43t5GSwA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYlhTM3dXbmsxdHlIR3Ry
        czJCYjFNUnNvbmRydkJNdkZMTnBNeTZ1OG1jClNxaDMwQ2svUFl0VXEwbFBsVU9Z
        ajVLUm93RjA4U0g0bjZETnZ0WGFBbzQKLS0tIERHSE9FMCtzN01yUHlWVHkwNXR4
        ZFluRU1mbGUwcndJbVpEaThGQ1NSOUUKZ4nSMtIH9h2h67LKb9ov9EExU+pM5Uoi
        Ld52tVZOk0+QDoNc06mBbJ8l7JBI6Q16Go5HTvTNidTQT7+ZPV4CQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T22:43:04Z"
  mac: ENC[AES256_GCM,data:5cUgVLWjEZLL6xBSLFPEBPSztQbp5NZrCUAepYN60slOOABLuUCsBLF16XvCLwDx173z+52k/MMHDLoB9ueMC61gNC5RVVdipW/aNPos1HMQ/2Rl3mbghfXib8OC5G97sAj3aIUt2BGecqqZx+Kh0IYnHKMuKlIsBjhHQ5+EnC0=,iv:9nEjlwQbyy8YNQw03PQdnt0fGKEFlMYDtC+a+j9O4eQ=,tag:W6IV973zcP1aIqWavX2BpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
