---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vaultwarden
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/vaultwarden/app
  components:
    - ../../../components/volsync
    - ../../../components/gatus/external
  # dependsOn:
  #   - name: crunchy-postgres-operator-cluster
  #     namespace: database

  postBuild:
    substitute:
      APP: *app
      # VOLSYNC_CAPACITY: 2Gi
      # VOLSYNC_START_MINUTE: "11"
      # VOLSYNC_CACHE_CAPACITY: "1Gi"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vaultwarden
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
    - name: haproxy
      namespace: rook-ceph-external
    - name: volsync
      namespace: storage
