---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/autobrr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app

---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/autobrr/app
  # components:
  #   - ../../../../components/volsync
  # - ../../../../components/gatus/guarded
  dependsOn:
    # - name: rook-ceph-cluster
    #   namespace: rook-ceph-external
    - name: volsync
      namespace: storage
  postBuild:
    substitute:
      APP: *app
    #   # GATUS_SUBDOMAIN: cloud
    #   VOLSYNC_CAPACITY: 5Gi
    #   # VOLSYNC_UID: "1022"
    #   # VOLSYNC_GID: "1022"
    #   VOLSYNC_START_MINUTE: "11"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 15m
