# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+WqUeXZZnjrHUVYxpYYEa2C98hiruq4gUivfeIXijk5rRMMn,iv:TflC6/OTlDAYzsReAEg+nDyzG1p4w09l0bphDFiCOXU=,tag:XRTEYsF73d0PHtlVXpDWVg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV05zVE12S25XbUdsazdC
        UDlHSzh2bjJmK0FmYlVRU21Gd2c2YTVqT2s4CmROK2lYRWFqWDNZdTAvaUFjRkVt
        UkE5d0NhTzBwK05DWEZyTERtVlpFekUKLS0tIG1HZ3dGaDhyc01XczlKYTlxUkVM
        VXhZamx5QldCR2hsNW9ERUZJcEpDbjQKSVaQrHHWM2WMxHx0Y7Rs9DKsfUXrHVEn
        SDYJLozMNi3upCHErgoV5MsEacxxN1gUqMgDXdNcIEGP6bbMW0ABsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T20:48:33Z"
  mac: ENC[AES256_GCM,data:rZ33UKGCNxeEhpPRvzAS7WAQ/Td3u6eB0sbzCyoJTrTrMws1Q+I9SiC0AxcQMZR4AyDOsKVpoY8q5bchC8PIwLiyWiSFDF+VwkHue2tB/EP2oqjJSDFhZG16BO3frW7S1XumfAvsxhbjh7YMte8289qY4qyyqApONNZWsilfnnI=,iv:2aGPjhOi1P53P6SaRwk1AL4QZP35uzxRgaWvOuyN/dM=,tag:5hAinPSF52QV50cflJJ1IA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
