# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:td9qOdeovMcxfaMF08dgvZBLDBiRB+UhJsdTYYlZLZVku0Luu8S3sA==,iv:1IyxAzIxUWrYSibzs2ZIf94SBzXd51sAOn9FOxoq/Sk=,tag:HkYAQoPrw562uqsMTkqx/A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSUI0WXVaUVkyd3dXM282
        KzhHKzhuMURoSDhTYkIxN2FqanJPdktHbEVjClc1aHp4WUZreTArV2oxTTlFZGx4
        UlZ5Y0JTTXo2aHRaaHk4ZlRlbUlZcTQKLS0tIDdRL21aQmtuVDRQM1k3czl5MkpR
        YUpzazUxZE9Kd2ZpMGFiOEdHaTBKemMK9UaZl7RfgBTR2KDt37xiCQJt71oS61QY
        2NtRZ2UqKSgadEvxY+Bz2tad/WBauozIO6U2ctxvMpVa4EmuMgD3Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:08:31Z"
  mac: ENC[AES256_GCM,data:WmXS+gT2wEntfSQwx9YQO8fXFl9Oc+xOybdgIukfcjGWKRCd1Dx+bzp0ztFlwwBuxed/1zqpEBb95pHfmumdeOq7Zq6oImFfGI0QpTN8VQ+g+ni8NYJCF6wbP9uverUd7Epv4gL1bwRA8cqJBsYCLNwOefedi/hI8Ltl2/z2po8=,iv:mq68L/dUMSCeQW5mBDLKmVuHT4ijLUQPl2zyGxsx00c=,tag:2HPWP1ckUUROVre8G2ba/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
