---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellystat
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: media
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/cyfershepard/jellystat
              tag: unstable@sha256:a0158927d1c5df68dbd98460bea68f491297ee5c1ff00a1204022554d8d363c6

            env:
              TZ: "${TIMEZONE}"
              MINIMUM_SECONDS_TO_INCLUDE_PLAYBACK: "30"

            envFrom:
              - secretRef:
                  name: jellystat-secret
              - secretRef:
                  name: jellystat-db-secret

            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 1Gi

    service:
      app:
        controller: main
        ports:
          http:
            port: &port 3000

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      backup:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /app/backend/backup-data
