---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radicale
spec:
  target:
    name: radicale-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: |-
          {{ .RADICALE_USR0 }}:{{ .RADICALE_USR0_PASS }}
  dataFrom:
    - extract:
        key: radicale
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
