---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radicale
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      radicale:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1003
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/ahinko/docker-radicale
              tag: 3.5.2

            resources:
              requests:
                cpu: 600m
                memory: 120M
              limits:
                memory: 512M

    service:
      app:
        controller: radicale
        ports:
          http:
            port: 5232

    ingress:
      app:
        className: external
        annotations:
          nginx.org/proxy-connect-timeout: 600s
          nginx.org/proxy-read-timeout: 600s
          nginx.org/proxy-send-timeout: 600s
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: calendars
          gethomepage.dev/group: apps
          gethomepage.dev/icon: sh-radicale.svg
          gethomepage.dev/name: radicale
        hosts:
          - host: &host "dav.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: radicale-config
        globalMounts:
          - path: /config/config
            subPath: config.cfg
            readOnly: true

      data:
        type: persistentVolumeClaim
        existingClaim: *app
        globalMounts:
          - path: /data

      auth:
        type: secret
        name: radicale-secret
        globalMounts:
          - path: /config/users
            subPath: users
            readOnly: true
