---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-secret
    template:
      data:
        # App
        nextcloud-username: "{{ .nextcloud_username }}"
        nextcloud-password: "{{ .nextcloud_password }}"
        # smtp_username: "{{ .smtp_username }}"
        # smtp_password: "{{ .smtp_password }}"
        # smtp_host: "{{ .smtp_host }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: nextcloud
        INIT_POSTGRES_HOST: postgres16-v3-rw.database.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: nextcloud
# spec:
#   target:
#     name: nextcloud-secret
#     template:
#       data:
#         # App
#         ADMIN_USER: "{{ .ADMIN_USER }}"
#         ADMIN_PASS: "{{ .ADMIN_PASS }}"
#         REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
#         SMTP_USERNAME: ""
#         SMTP_PASSWORD: ""
#         SMTP_HOST: smtp-relay.default.svc.cluster.local
#         # Database
#         POSTGRES_HOST: '{{ index . "host" }}'
#         POSTGRES_USER: '{{ index . "user" }}'
#         POSTGRES_PASSWORD: '{{ index . "password" }}'
#         POSTGRES_DB: '{{ index . "dbname" }}'
#         # OIDC
#         # OIDC_CLIENT_ID: nextcloud
#         # OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_OAUTH_CLIENT_SECRET }}"
#   dataFrom:
#     - extract:
#         key: dragonfly
#       sourceRef: &onepassword
#         storeRef:
#           kind: ClusterSecretStore
#           name: onepassword
#     - extract:
#         key: nextcloud
#       sourceRef: *onepassword
#     - extract:
#         key: postgres-16-pguser-nextcloud
#       sourceRef:
#         storeRef:
#           kind: ClusterSecretStore
#           name: crunchy-pgo-secrets
