---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  target:
    name: nextcloud-secret
    template:
      data:
        # App
        ADMIN_USER: "{{ .NXC_ADMIN_USER }}"
        ADMIN_PASS: "{{ .NXC_ADMIN_PASS }}"
        REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        SMTP_USERNAME: ""
        SMTP_PASSWORD: ""
        SMTP_HOST: smtp-relay.default.svc.cluster.local
        # Database
        POSTGRES_HOST: '{{ index . "host" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_DB: '{{ index . "dbname" }}'
        # OIDC
        OIDC_CLIENT_ID: NXC_AK_CLIENT_ID
        OIDC_CLIENT_SECRET: "{{ .NXC_AK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: dragonfly
      sourceRef: &onepass
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: nextcloud
      sourceRef: *onepass
    - extract:
        key: postgres-pguser-nextcloud-1
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
