---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  target:
    name: vikunja-secret
    template:
      data:
        # App
        VIKUNJA_SERVICE_JWT_SECRET: "{{ .VIKUNJA_JWT_SECRET }}"
        VIKUNJA_REDIS_DB: "{{ .DF_REDIS_VIKUNJA_DB }}"
        VIKUNJA_REDIS_HOST: "{{ .DF_HOST }}:{{ .DF_REDIS_PORT }}"
        # mail
        VIKUNJA_MAILER_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        VIKUNJA_MAILER_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        VIKUNJA_MAILER_USERNAME: "{{ .EXTERNAL_SMTP_USER }}"
        VIKUNJA_MAILER_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        VIKUNJA_MAILER_FROMEMAIL: "Vikunja <{{ .EXTERNAL_SMTP_FROM_EMAIL }}>"
        # Database
        VIKUNJA_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        VIKUNJA_DATABASE_USER: '{{ index . "user" }}'
        VIKUNJA_DATABASE_PASSWORD: '{{ index . "password" }}'
        VIKUNJA_DATABASE_DATABASE: '{{ index . "dbname" }}'
        # OIDC
        config.yaml: |
          auth:
            openid:
              enabled: true
              redirecturl: https://vikunja.${SECRET_DOMAIN}/auth/openid/
              providers:
                - name: Authentik
                  authurl: "https://sso.${SECRET_DOMAIN}/application/o/vikunja/"
                  logouturl: "https://sso.${SECRET_DOMAIN}/application/o/vikunja/end-session/"
                  clientid: {{ .VIKUNJA_AK_CLIENT_ID }}
                  clientsecret: {{ .VIKUNJA_AK_CLIENT_SECRET }}
  dataFrom:
    - extract:
        key: dragonfly
      sourceRef: &onepass
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: vikunja
      sourceRef: *onepass
    - extract:
        key: external-smtp
      sourceRef: *onepass
    - extract:
        key: crunchy-postgres-pguser-vikunja
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
