---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vikunja:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret vikunja-secret
        containers:
          app:
            image:
              repository: vikunja/vikunja
              tag: 0.24.6@sha256:ed1f3ed467fecec0b57e9de7bc6607f8bbcbb23ffced6a81f5dfefc794cdbe3b

            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                memory: 512Mi

            envFrom:
              - secretRef:
                  name: *secret
            env:
              TZ: ${TIMEZONE}
              VIKUNJA_AUTH_LOCAL: false
              VIKUNJA_DATABASE_TYPE: postgres
              VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_NAME: true
              VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_ENABLED: false
              VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
              VIKUNJA_REDIS_ENABLED: true
              VIKUNJA_KEYVALUE_TYPE: redis
              VIKUNJA_MAILER_ENABLED: true
              VIKUNJA_SERVICE_PUBLICURL: https://vikunja.${SECRET_DOMAIN}
              VIKUNJA_SERVICE_TIMEZONE: ${TIMEZONE}
              VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: true
              VIKUNJA_SERVICE_ENABLEREGISTRATION: false
              VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: true
              VIKUNJA_BACKGROUNDS_PROVIDERS_UNSPLASH_ENABLED: true
              VIKUNJA_METRICS_ENABLED: true

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/info
                    port: &port 3456
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3456

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Vikunja
          gethomepage.dev/description: Tasks and project management platform.
          gethomepage.dev/group: apps
          gethomepage.dev/icon: sh-vikunja.svg
          gethomepage.dev/pod-selector: >-
            app in (
              vikunja
            )
        hosts:
          - host: &host "vikunja.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      tailscale:
        className: tailscale
        hosts:
          - host: &tshost "{{ .Release.Name }}.${SECRET_TS_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *tshost

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /app/vikunja/files

      vikunja-config:
        type: secret
        name: *secret
        globalMounts:
          - path: /app/vikunja/config.yaml
            subPath: config.yaml
            readOnly: true
