---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        DATABASE_URL: postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASSWORD }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/litellm
        REDIS_URL: redis://dragonfly.database.svc.cluster.local
  dataFrom:
    - find:
        name:
          regexp: ^LITELLM.*
    - find:
        path: POSTGRES_SUPER_HOST_RW

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-postgres-secret
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

        # LITELLM Postgres Init
        INIT_POSTGRES_DBNAME: &dbName litellm
        INIT_POSTGRES_USER: &dbUser "{{ .LITELLM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .LITELLM_POSTGRES_PASSWORD }}"

        # App Postres
        DATABASE_URL: postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASSWORD }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/litellm
        DB_POSTGRESDB_DATABASE: *dbName
        DB_POSTGRESDB_HOST: *dbHost
        DB_POSTGRESDB_USER: *dbUser
        DB_POSTGRESDB_PASSWORD: *dbPass

  dataFrom:
    - find:
        name:
          regexp: ^LITELLM.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
