# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: e1000e-fix-app
#   namespace: flux-system
#   labels: &l
#     app.kubernetes.io/name: "e1000e-fix"
# spec:
#   commonMetadata:
#     labels: *l
#   path: ./kubernetes/apps/network/e1000e-fix/app
#   targetNamespace: "network"
#   # dependsOn: []

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app e1000e-fix-app
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/network/e1000e-fix/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
  interval: 30m
  timeout: 5m
