# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XJbmtUxEFyIbehWqdNnaHkqx5BSElVG4YJnMMSxOrrw=,iv:06697/omVoMib0xIYBhut3snMEQdPUG2XyiObLU/XQU=,tag:Bh7VZq/RKc5TPg/4DhW/ug==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUHNoWkpsVW00T09BdHNV
        elR5V1l4T3hNOHB5NWoyTEFzVGRrMHdiU1FBCmZLVkZGaWdRc2J2MmNaRlh3SzRG
        M1AyTFEwRHJWNkVWeDZEMTFISU5ZdGMKLS0tIFd0TENEc21STlNkbTNhVkxHK01Z
        NmgzbTN6a0RiakVjTm5HK0k3anNFODAKVPN8c3EWBceusiePb+oR5Vsp4/TNub2B
        lACpsg2zn1VYC25JIt7BYuUKD8rK9Ym11DOidmnbiLft04/nokJfHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T20:48:33Z"
  mac: ENC[AES256_GCM,data:xUR1y0amQd4OquBMxpPXcRT1cihVw8ptxZMZ+eWHyg11f6VVAOnlTC3IcdrWwr4kVBhZYrKOHcLpn0qX3yR86UYLww/5z/w49NFCF9JlGP3g3+Tt5YHrQX8k45QkIvj9UmM1xgAdbXbInpds6dqo40OT8o05ABSGhezvxMxJoQw=,iv:+ovXJwSyr/fCe3P8n70fv3EffmetnnsS7itxT3tiApc=,tag:cDXKstWhGFRcc5ZDTdgG1g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
