# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openwebui
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
      namespace: storage
  path: ./kubernetes/apps/ai/open-webui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      GATUS_SUBDOMAIN: ai
      GATUS_DOMAIN: ${SECRET_DOMAIN}
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
