---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace security
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/security/authentik/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
    - name: onepassword-store
      namespace: external-secrets
  components:
    - ../../../../components/gatus/external
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sso
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
