---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        PUSHOVER_TOKEN: "{{ .alertmanager_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_bernd }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: Pushover
    # - extract:
    #     key: qbittorrent
