---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  target:
    name: authentik-secret
    template:
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AK_ADMIN_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AK_ADMIN_PASS }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AK_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AK_SECRET_KEY }}"
        AUTHENTIK_REDIS__DB: "1"
        # Database
        AUTHENTIK_POSTGRESQL__NAME: '{{ index . "dbname" }}'
        AUTHENTIK_POSTGRESQL__HOST: '{{ index . "host" }}' #pgBouncer is set to session for Grafana, and Authentik requires transaction
        AUTHENTIK_POSTGRESQL__USER: '{{ index . "user" }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ index . "password" }}'
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "false"
        AUTHENTIK_POSTGRESQL__SSLMODE: "require"
        # email
        AUTHENTIK_EMAIL__HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .EXTERNAL_SMTP_USER }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        AUTHENTIK_EMAIL__USE_SSL: "true"
        AUTHENTIK_EMAIL__FROM: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
  dataFrom:
    - extract:
        key: authentik
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: external-smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-authentik
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
