---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.4.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom: &envFrom
        - secretRef:
            name: *secret
    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
    server:
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 400m
        limits:
          memory: 1G
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        # annotations:
        #   gethomepage.dev/enabled: "true"
        #   gethomepage.dev/icon: authentik.png
        #   gethomepage.dev/name: Authentik
        #   gethomepage.dev/group: infra
        #   gethomepage.dev/app: authentik
        #   gethomepage.dev/description: OIDC User Management
        #   gethomepage.dev/widget.type: authentik
        #   gethomepage.dev/widget.url: http://authentik-server.security
        #   gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SVC_AK_TOKEN}}"
        hosts:
          - sso.${SECRET_DOMAIN}
        https: false
    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 400m
        limits:
          memory: 2G
