---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wyoming-whisper
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: rhasspy/wyoming-whisper
              tag: latest
            args:
              - --model
              - base
              - --language
              - en
            env:
              TZ: ${TIME_ZONE}
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.feature.node.kubernetes.io/gpu
                  operator: In
                  values:
                    - "true"
    nodeSelector:
      nvidia.feature.node.kubernetes.io/gpu: "true"
    runtimeClassName: nvidia
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 150
        fsGroup: 140
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          whisper:
            enabled: true
            primary: true
            port: 10300
            protocol: TCP
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
