# yaml-language-server: $schema=http://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pihole-exporter:
        containers:
          pihole-exporter:
            image:
              repository: ghcr.io/osnabrugge/pihole-exporter #ekofr/pihole-exporter
              tag: v1.2.0@sha256:cbf4519e28499b35c1f7b332a9652b5cd582f5e17bdfeaffeaf19abb76886063 #latest@sha256:61bd07030394a4cf069d5a19cd5f4d62180e9f25fd6e0e159af5ed90021fd7d3
            env:
              PIHOLE_HOSTNAME: 192.168.86.100
              PORT: &port 9617
              PIHOLE_PORT: "1080"
              PIHOLE_PROTOCOL: http
            envFrom:
              - secretRef:
                  name: pihole-exporter-secret
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 60M
    service:
      pihole-exporter:
        controller: pihole-exporter
        ports:
          http:
            port: *port
    serviceMonitor:
      pihole-exporter:
        serviceName: pihole-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m
            scrapeTimeout: 1m
