---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  components:
    - ../../../../flux/components/gatus/guarded
    - ../../../../flux/components/volsync
  dependsOn:
    - name: volsync
      namespace: storage
    - name: cloudnative-pg
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/ai/n8n/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      GATUS_SUBDOMAIN: n8n
      GATUS_DOMAIN: ${SECRET_DOMAIN}
