---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/ai/n8n/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  postBuild:
    substitute:
      APP: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/guarded
