---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: "{{ .api_key }}"
        PROWLARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
        PROWLARR__POSTGRES__HOST: '{{ index . "host" }}'
        PROWLARR__POSTGRES__USER: '{{ index . "user" }}'
        PROWLARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        PROWLARR__POSTGRES__PORT: '{{ index . "port" }}'
  dataFrom:
    - extract:
        key: prowlarr
    - extract:
        key: postgres-16-pguser-prowlarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
