---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: "{{ .api_key }}"
        PROWLARR__POSTGRES__HOST: "postgres-primary-real.database.svc"
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: "{{ .PROWLARR_POSTGRES_USER }}"
        PROWLARR__POSTGRES__PASSWORD: "{{ .PROWLARR_POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES__MAINDB: prowlarr_main
  dataFrom:
    - extract:
        key: prowlarr
