---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_PROV_OWM_API: "{{ .OWM_SECRET }}"
        HOMEPAGE_VAR_PROV_WAPI_API: "{{ .WAPI_API_KEY }}"
        HOMEPAGE_VAR_WID_UBI_USER: "{{ .HP_UBI_USER }}"
        HOMEPAGE_VAR_WID_UBI_PASS: "{{ .HP_UBI_PASS }}"
        HOMEPAGE_VAR_WID_HOUSE_LAT: "{{ .HOME_LAT }}"
        HOMEPAGE_VAR_WID_HOUSE_LONG: "{{ .HOME_LONG }}"

        ## services
        ### proxmox
        HOMEPAGE_VAR_SVC_PROX_URL: "{{ .HP_PM_URL }}"
        HOMEPAGE_VAR_SVC_PROX_USER: "{{ .HP_PM_TOKEN }}"
        HOMEPAGE_VAR_SVC_PROX_PASS: "{{ .HP_PM_SECRET }}"

        ### unraid
        HOMEPAGE_VAR_SVC_UNRAID_URL: "{{ .HP_UNRAID_URL }}"

        ### traefik
        HOMEPAGE_VAR_SVC_TRAEFIK_URL: "{{ .HP_TFK_URL }}"

        ### portainer
        HOMEPAGE_VAR_SVC_PORT_URL: "{{ .PORT_URL }}"
        HOMEPAGE_VAR_SVC_PORT_ENV: "{{ .HP_PORT_ENV }}"
        HOMEPAGE_VAR_SVC_PORT_PASS: "{{ .HP_PORT_SECRET }}"

        ### adguard home
        HOMEPAGE_VAR_SVC_AGH_A_URL: "{{ .HP_AGH_A_URL }}"
        HOMEPAGE_VAR_SVC_AGH_A_USER: "{{ .HP_AGH_A_TOKEN }}"
        HOMEPAGE_VAR_SVC_AGH_A_PASS: "{{ .HP_AGH_A_SECRET }}"

        HOMEPAGE_VAR_SVC_AGH_B_URL: "{{ .HP_AGH_B_URL }}"
        HOMEPAGE_VAR_SVC_AGH_B_USER: "{{ .HP_AGH_B_TOKEN }}"
        HOMEPAGE_VAR_SVC_AGH_B_PASS: "{{ .HP_AGH_B_SECRET }}"

        HOMEPAGE_VAR_SVC_AGSYNC_URL: "{{ .HP_AGS_URL }}"
        HOMEPAGE_VAR_SVC_AGSYNC_API_URL: "{{ .HP_AGS_API_URL }}"

        ### technitium
        HOMEPAGE_VAR_SVC_TNTM_1_URL: "{{ .TNTM_1_URL }}"
        HOMEPAGE_VAR_SVC_TNTM_1_PASS: "{{ .TNTM_1_HP_API_SECRET }}"

        HOMEPAGE_VAR_SVC_TNTM_2_URL: "{{ .TNTM_2_URL }}"
        HOMEPAGE_VAR_SVC_TNTM_2_PASS: "{{ .TNTM_2_HP_API_SECRET }}"

        ### nextdns
        HOMEPAGE_VAR_SVC_NDNS_URL: "{{ .NDNS_URL }}"
        HOMEPAGE_VAR_SVC_NDNS_PROFILE: "{{ .NDNS_PROFILE }}"
        HOMEPAGE_VAR_SVC_NDNS_PASS: "{{ .NDNS_HP_API_SECRET }}"

        ### uptimekuma
        HOMEPAGE_VAR_SVC_UPKU_URL: "{{ .UPKU_URL }}"
        HOMEPAGE_VAR_SVC_UPKU_SLUG: "{{ .UPKU_HP_SLUG }}"
        HOMEPAGE_VAR_SVC_UPKU_PASS: "{{ .UPKU_HP_API_SECRET }}"

        ### proxmox backup
        HOMEPAGE_VAR_SVC_PBS_URL: "{{ .PBS_URL }}"
        HOMEPAGE_VAR_SVC_PBS_USER: "{{ .PBS_HP_TOKEN }}"
        HOMEPAGE_VAR_SVC_PBS_PASS: "{{ .PBS_HP_SECRET }}"

        ### peanut
        HOMEPAGE_VAR_SVC_PNUT_URL: "{{ .PNUT_A_URL }}"
        HOMEPAGE_VAR_SVC_PNUT_KEY: "{{ .PNUT_A_KEY }}"

        ### gitea
        HOMEPAGE_VAR_SVC_GITEA_HREF_URL: "{{ .GITEA_HOME_URL }}"
        HOMEPAGE_VAR_SVC_GITEA_LOCAL_URL: "{{ .GITEA_LOCAL_URL }}"
        HOMEPAGE_VAR_SVC_GITEA_PASS: "{{ .GITEA_HP_SECRET }}"

        ### paperless
        HOMEPAGE_VAR_SVC_PPRL_URL: "{{ .PPRL_URL }}"
        HOMEPAGE_VAR_SVC_PPRL_PASS: "{{ .PPRL_HP_SECRET }}"
        HOMEPAGE_VAR_SVC_PPRL_2_PASS: "{{ .PPRL_2_HP_SECRET }}"

        ### netbox
        HOMEPAGE_VAR_SVC_NETBOX_URL: "{{ .NETBOX_URL }}"
        HOMEPAGE_VAR_SVC_NETBOX_GLANCE_URL: "{{ .NETBOX_GLANCE_URL }}"
        HOMEPAGE_VAR_SVC_NETBOX_EXT_URL: "{{ .NETBOX_EXT_URL }}"

        ### calibre-web
        HOMEPAGE_VAR_SVC_CWEB_USER: "{{ .CW_ADMIN_USER }}"
        HOMEPAGE_VAR_SVC_CWEB_PASS: "{{ .CW_ADMIN_PASS }}"

        ### grafana
        HOMEPAGE_VAR_SVC_GFN_USER: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_SVC_GFN_PASS: "{{ .GRAFANA_ADMIN_PASSWORD }}"

        ### authentik
        HOMEPAGE_VAR_SVC_AK_TOKEN: "{{ .AK_TOKEN }}"

        ### homebox
        HOMEPAGE_VAR_SVC_HBX_USER: "{{ .HBX_LOGIN_USER }}"
        HOMEPAGE_VAR_SVC_HBX_PASS: "{{ .HBX_LOGIN_PASS }}"

        ### cups
        HOMEPAGE_VAR_SVC_CUPS_URL: "{{ .CUPS_URL }}"

        ### ARR
        HOMEPAGE_VAR_SVC_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_SVC_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SVC_BAZARR_TOKEN: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_SVC_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"

        HOMEPAGE_VAR_SVC_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"

        # lubelog
        HOMEPAGE_VAR_SVC_LUBEL_USERNAME: "{{ .LUBEL_HP_USER }}"
        HOMEPAGE_VAR_SVC_LUBEL_PASSWORD: "{{ .LUBEL_HP_PASS }}"

        HOMEPAGE_VAR_SVC_NXC_TOKEN: "{{ .NXC_METRICS_TOKEN }}"

        HOMEPAGE_VAR_SVC_MNFX_TOKEN: "{{ .MNFX_HP_TOKEN }}"

  dataFrom:
    - extract:
        key: house
      sourceRef: &op
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: homepage
      sourceRef: *op
    - extract:
        key: openweathermap
      sourceRef: *op
    - extract:
        key: weatherapi
      sourceRef: *op
    - extract:
        key: house
      sourceRef: *op
    - extract:
        key: proxmox
      sourceRef: *op
    - extract:
        key: portainer
      sourceRef: *op
    - extract:
        key: adguard-home
      sourceRef: *op
    - extract:
        key: adguard-sync
      sourceRef: *op
    - extract:
        key: technitium
      sourceRef: *op
    - extract:
        key: nextdns
      sourceRef: *op
    - extract:
        key: uptime-kuma
      sourceRef: *op
    - extract:
        key: proxmox-backup-server
      sourceRef: *op
    - extract:
        key: peanut
      sourceRef: *op
    - extract:
        key: gitea
      sourceRef: *op
    - extract:
        key: paperless
      sourceRef: *op
    - extract:
        key: netbox
      sourceRef: *op
    - extract:
        key: authentik
      sourceRef: *op
    - extract:
        key: calibre-web
      sourceRef: *op
    - extract:
        key: grafana
      sourceRef: *op
    - extract:
        key: homebox
      sourceRef: *op
    - extract:
        key: traefik
      sourceRef: *op
    - extract:
        key: unraid
      sourceRef: *op
    - extract:
        key: cups
      sourceRef: *op
    - extract:
        key: sonarr
      sourceRef: *op
    - extract:
        key: radarr
      sourceRef: *op
    - extract:
        key: sabnzbd
      sourceRef: *op
    - extract:
        key: bazarr
      sourceRef: *op
    - extract:
        key: prowlarr
      sourceRef: *op
    - extract:
        key: nextcloud
      sourceRef: *op
    - extract:
        key: lubelog
      sourceRef: *op
    - extract:
        key: miniflux
      sourceRef: *op
