---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gonic
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        # pod:
        #   securityContext:
        #     supplementalGroups:
        #       - 1000
        containers:
          main:
            image:
              repository: ghcr.io/sentriz/gonic
              tag: v0.17.0@sha256:32c400a21b107bc3b87a49ec9af591a37d7f9cc03ee83d68a379ee76bb716607
            env:
              GONIC_SCAN_INTERVAL: "120"
              GONIC_PLAYLISTS_PATH: /Media/playlists
              GONIC_MUSIC_PATH: /Media/chrisadmin/files/Music
              GONIC_PODCAST_PATH: /Media/podcasts
            resources:
              requests:
                cpu: 15m
                memory: 800M
              limits:
                memory: 800M
    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 80
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host gonic.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /data
      media:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: "/mnt/datastore/nextcloud"
        globalMounts:
          - path: /Media
