---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        DB_POSTGRESDB_DATABASE: n8n
        DB_POSTGRESDB_HOST: "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        DB_POSTGRESDB_USER: "{{ .N8N_POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: "{{ .N8N_POSTGRES_PASSWORD }}"
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"

  dataFrom:
    - find:
        name:
          regexp: ^N8N.*
    - find:
        path: POSTGRES_SUPER_HOST_RW

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: n8n-postgres-secret
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

        # N8N Postgres Init
        INIT_POSTGRES_DBNAME: &dbName n8n
        INIT_POSTGRES_USER: &dbUser "{{ .N8N_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .N8N_POSTGRES_PASSWORD }}"

        # App Postres
        DATABASE_URL: postgresql://{{ .N8N_POSTGRES_USER }}:{{ .N8N_POSTGRES_PASSWORD }}@{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local/n8n
        DB_POSTGRESDB_DATABASE: *dbName
        DB_POSTGRESDB_HOST: *dbHost
        DB_POSTGRESDB_USER: *dbUser
        DB_POSTGRESDB_PASSWORD: *dbPass

  dataFrom:
    - find:
        name:
          regexp: ^N8N.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
