---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-files
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: mayastor-single-replica
