---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .api_key }}"
        PUSHOVER_TOKEN: "{{ .radarr_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        RADARR__POSTGRES__HOST: "postgres-primary-real.database.svc"
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: "{{ .RADARR_POSTGRES_USER }}"
        RADARR__POSTGRES__PASSWORD: "{{ .RADARR_POSTGRES_PASSWORD }}"
        RADARR__POSTGRES__MAINDB: radarr_main
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: radarr
