---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .api_key }}"
        PUSHOVER_TOKEN: "{{ .alertmanager_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_bernd }}"
        RADARR__POSTGRES__HOST: '{{ index . "host" }}'
        RADARR__POSTGRES__PORT: '{{ index . "port" }}'
        RADARR__POSTGRES__USER: '{{ index . "user" }}'
        RADARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        RADARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: Pushover
    - extract:
        key: radarr
    - extract:
        key: postgres-16-pguser-radarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
