---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  # []
  - ./actual/ks.yaml
  # - ./atuin/ks.yaml
  # - ./gramps/ks.yaml
  # - ./miniflux/ks.yaml
  - ./n8n/ks.yaml
  # - ./nextcloud/ks.yaml
  - ./syncthing/ks.yaml
