---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tailscale
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/network/tailscale/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  targetNamespace: *namespace
  wait: false
  interval: 30m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-operator-config
  namespace: network
spec:
  interval: 1h
  dependsOn:
    - name: tailscale
  targetNamespace: *network
  path: ./kubernetes/apps/network/tailscale/config
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system