---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bazarr-secret
    template:
      engineVersion: v2
      data:
        JELLYFIN_TOKEN: "{{ .JELLYFIN_TOKEN }}"
        POSTGRES_DATABASE: '{{ index . "dbname" }}'
        POSTGRES_HOST: '{{ index . "host" }}'
        POSTGRES_USERNAME: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_PORT: '{{ index . "port" }}'      

        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass

  dataFrom:
    - extract:
        key: jellyfin
    - extract:
        key: postgres-16-pguser-bazarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets