---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bazarr-secret
    template:
      engineVersion: v2
      data:
        JELLYFIN_TOKEN: "{{ .JELLYFIN_TOKEN }}"
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_USERNAME: &dbUser "{{ .BAZARR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .BAZARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: jellyfin
    - extract:
        key: bazarr

        SONARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
        SONARR__POSTGRES__LOGDB: sonarr_log
        SONARR__POSTGRES__HOST: '{{ index . "host" }}'
        SONARR__POSTGRES__USER: '{{ index . "user" }}'
        SONARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        SONARR__POSTGRES__PORT: '{{ index . "port" }}'
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: postgres-16-pguser-sonarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets