apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/m+pVUA8o9rL2Q==,iv:BH3pPvvY/MkZak/jDQqHlssc8W45pfa8BM64Lz6Qi2Q=,tag:LHTbXw6t8H7UdJtTsf7vAg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYUl4WWsxSFZ3R0RDVmh4
        NXFKa3RhakdPTWp3cjh5VVJRN2VIQTZKNUNFCmNNVU1rckdxUU5kRGRxSjZaRzEz
        Z1lBRi9idXN0NExFTEZYQ0JtVXkzVjQKLS0tIFpWMTV1SUxkVENTRzBnTHFhWFZF
        V2JqbjdrRXhxTVBCK083Q3ZQRkZwUlUKCVfw1nz65+lmSxVLISDJYaXAViJ3H31E
        Ois++DGWfFbFOne4IdnC4cdtOsKzNHRt+Q0RK1QD+EXOBQ/NH5tIRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:08:31Z"
  mac: ENC[AES256_GCM,data:qbV6NctGr6chm7sZTtshYHOuueBa2S5tkimDadPRQaPSw9bKLVQtnDgvLqo4bZ6OgK5TkcTYN5ocMVe8XxakRIDI0JlZ/8JyMeACOy+DzOj5LomT9xEugz/iFTkUDn1gu5o7Sro6WenKFmDb5mvOtnV1SR1MTYDTlLVpJzekB6Y=,iv:AVSa9VmPozX4BCk82LgiMfNnzpYzY83QE4s7R0waM3g=,tag:1p7yh885fZ1lWJa87Ck/GA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
