apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:MozD1tfBiguYVQ==,iv:a2GXut1uUch4sWCdTY4puAaT7IfO+G1sJbd0sR75vU8=,tag:54MSaf9/kktVuTPjtWGiWg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T25tDb6NRGXZna6yqCu6iz3isJqNO4jIDGo7seAn4lcnq3RN,iv:bKofX9o6SHnBFNiRd60lMFN36REjmbnB29RYclmoLFA=,tag:dfGXxFcVwo1fbCp3Tfw5Jg==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:Uowj+Vn0yOP2/5j6hruv8odUhHoIiOLtJWMYUMJ9lHLyZDLV,iv:6s9+ziKhinDi9Xs3yFkobXrM8/+hojGibycpwgCX2t0=,tag:F6eJke/FS+xkQADX0KhKrQ==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:WjYqE7e/es6OPpjO,iv:3f9Edg4ayQhiCVDp8UGnP8pOpW8Kl4AaveGQwweEOoM=,tag:Da6a0JsoHgejw+4vbdkNzA==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:MIDKvPq0278daXOAd4/OJ8ZEISY=,iv:v02LFJtz3Q9tU3XE23exZnzPOtN50n+nejZic7xxQas=,tag:MWH1SQcQPowo5v3MsdIplw==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:G6p++PRQuJfq4JBPT4B1R8z/2WUaV2oJv2z4x8victk0eAVJuNMyfQ==,iv:1nqk4bNQDGlale1O5ZCWz80B2cN93HfLtY5tBGsVfp4=,tag:xMu1zilaiZB6Zfu74gV33A==,type:str]
  CPGO_R2_ENDPOINT: ENC[AES256_GCM,data:jyWcv0/TDF/rVAhb86SBVMPh22iiJl0uNP2akL+7LgpRSwf4I1lJ/hlEDMstMILJRbIZx9nsIjiYu4Xg4QdOzso=,iv:HS9/hZ/Pnt8/lQsrc1W4E+ACZBWYp/fAOu2cX56KDgQ=,tag:uHc8naBoSFP9utaD4zfZ7A==,type:str]
  RANCHERBOOTSRAPCODE: ENC[AES256_GCM,data:6uuZFRLj8lRo0iRL60w=,iv:YNy+wJz2lyEroDdl8KkgpHKJhp34uhsv0y5N+Wiqf34=,tag:ZK3mmE02zkylZY1GW0vmxw==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:eI9pzXT/14QMgYdDNkRXAX7s5Y60les1Fuz1gtzh,iv:m1R7CASdJ7YEx+ZjkW+ohnuItlkvkppFoJy6jRrccUg=,tag:JTdyLEQJIIgC1IjsytuC1g==,type:str]
  PUSHOVER_KEY: ENC[AES256_GCM,data:1ftPnzvGEJ/fhdk281AG7zemOPKffAX7n6oRf9kJ,iv:4pmZFpoe4XyEpLPBYMdNB8E/saBShDon0HJfIX6Iqcc=,tag:5oDDqAblDdOOoyjWQzFhBw==,type:str]
  NAS_IP: ENC[AES256_GCM,data:uST79dMQl+K143S3U+U=,iv:x8zlsi2RKhzZbPT9hFz0JNmHCr08OBP9T+b2zCq3mpk=,tag:IC/aag091llShwaLxw1xyw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:VGRVWBX5ALGCZA7h7S8vKTZ88w==,iv:H2622ESi4UOs4ODBOTzepWM/L+JPnGmYZ6ngSrBjuuQ=,tag:RGCLKnjVHmN5HfvLDxz+EQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVlREU0Q4QmJaWEJib01l
        VndTR1hhdlVnYVRFNjgxYXc1WHV3QmFEemxNCmlFK2NYdHBjeEZNNk5waHhtZ2lu
        Q1dzcWJFNTdybzRSMzM1c2NtRURiQlUKLS0tIE52eFFPcU9INDVjQkZVRlhFMEVQ
        TFJGcmFKSnNMTUsxU053ZnlpcmhYVW8KBnejBPuJN9G6H4fJFR+SrURDZy81pKpq
        Lx6ygZNYyNZT+pv3DtOKVKVd13GRh5UsJcH1ZA4AbZE4+dThXBJhog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-01T20:56:26Z"
  mac: ENC[AES256_GCM,data:4u08o4oLX3F14a87jSCBxz4rKomgb897j9sNGGKvkh3NJLyc9P4QpIlRMwpxju1fVOZJdopIRVdLZFQd+HjhMrm2mj5CvguWEJwFkUbtZZWRWGUL/U+PrdiwFZ5aNdD6OmZkWFuZW91lGAvjzIWCaF+yihA8aXwALSzWqPGmlpk=,iv:a8UYOcAHnx2jLygLY7BjykHtDNEyonwp+dhDn97eDX8=,tag:kECuhWlmv+WZiwkq5twG/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
