apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Qy18QtkLm4aHKA==,iv:8azXLRg+6doGe/9aflNiy/7FHOBGIQc2t7EgJmSWI88=,tag:2jqNjQaJ5QUjudS5XdLLrA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OOTwfTq2GgmdyEDvzHfqvlVwctFnzM2j8kJwPdB+NiMkp9n9,iv:FpU24DseI8Ic0sPVPED7+fv/2R3sWxHMyXzWVnXBuos=,tag:98mOCm3CR8k8uVwOkiIkZg==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:2n1zPQF6Usdxgb42B8BkcLVeiJgn9BxVm3Ee/ru1R2sxq4yE,iv:cEfAEh+y21J91XW5GMD1Z4zjb1qBvGnuXLSRhToMmAU=,tag:iD8jLqwZEosO4oB+MozAAg==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:MXQqQ8DO51Osq/YA,iv:g8zCe4UFAgz0/az2ugGoyTI9v3+H7JtASGigLD9/5aE=,tag:mJJjCsyF5N0SlJ/8QDDazw==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:qslY0IO4lpnO5SecFGSvryk5k68=,iv:1nZ+eFavlAmK3dQqp2THjxQD8EcWlar7Kjmxe3baOXw=,tag:SDiHpvh7cM07XA8pbV27TA==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:8seTr5FzfTZrUz/VYpbuSWXwJ5CcBr/N3NAHWspXPoAGoalmyrplhQ==,iv:9lOIBttDEqSVT1RMiONth0VSILrsPXKdJRfH5omSw0A=,tag:qdp5YkPAM6HMR5fQngT1Gg==,type:str]
  CPGO_R2_ENDPOINT: ENC[AES256_GCM,data:6vaiIdm4bh5uSxq2HmSKC8SW3GUf2QYvdb8XCwWeM2OY/Ofu689a9h2sVfKz/3I1zBi/8uWegA5D4EcBeOtKoQE=,iv:lVJ7nhFdpJffFsNmlP3g0k6RyncE8kgaFjvX4vjBcDo=,tag:wLvUsqOgqAFd8Mi7LJ7Ohg==,type:str]
  RANCHERBOOTSRAPCODE: ENC[AES256_GCM,data:nvIx/6mBotRG3RTZjAc=,iv:JgX2nA7vclAhbE0sFWt9Oh7DgiwSX9JudY8pehuPuac=,tag:4VM1x2ttt2Ye9LSIWv5YGw==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:ovnoynqRvsj8HPtDc6NbYPwCtGgTpok6Fsvuxgu1,iv:qg7kZhFNZrQb2irUEJrmP+TRKH3zMl8XAC12mPsN6Vw=,tag:3NESeargkz1BRlzDdtBz3g==,type:str]
  PUSHOVER_KEY: ENC[AES256_GCM,data:0yGD2o17Ms8K5Ne23ey1/sG5mcXQjvZGwpmqC3+P,iv:835+qTlXnn4NeRoSY0t1qJvXqafKM2EgoBL/O7siDEw=,tag:+X7hI5VdBOfOKImNcRn0Hg==,type:str]
  NAS_IP: ENC[AES256_GCM,data:maCUUwKJMKQZenUTuZc=,iv:C7VnhZQu5bP5iGY/JJV/kaT5BFww/Nzytx2dHZHiDGs=,tag:JEMvh7tRYbmqiAhIskxELQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:RJ9X/0KbFD/asAHePfqFMrtrBA==,iv:d3llkHJDacd1XspGTUejbLd6ZAh4dnu551iM/oWDXB4=,tag:+BqIzNepKm253DPFyqln8g==,type:str]
  R2_KEY: ENC[AES256_GCM,data:O9tM3ChrrdkeIh/4hHwJ18z+laYLJdhlm017gkSliMo=,iv:P53XPCajb8jEA6ktxzhVoGP8ulo36kZDSOB/WyN0Ma4=,tag:YWP3mnVH/SnZYIP+TUtx1w==,type:str]
  R2_SECRET_KEY: ENC[AES256_GCM,data:tPdnlOxLVmGRWuEClllzrw8fSrkqXR8kwMtY4v29HB5sHnRMJzYLF0SGX5PfD0ptCooCvDjMio2IzN6tmQ5yxQ==,iv:EphmkLHjN4cHnN/dOa40OP/Q3tWBiYpC1Uf1uR9G3ns=,tag:HfhHLe8N05yM7ehFksSHgQ==,type:str]
  MINIO_KEY: ENC[AES256_GCM,data:+A6CUmmjRU/4Fb++uKmU1V/2Th8=,iv:aM3RPYjB08Mdf6TxA/VdYIleshrwixc27Zmxa6X3mpk=,tag:azEHKs7ZNVwVzXLZi6kz2Q==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:mH5r1ZFKhgS0sreQBGqdYvMHIyStR2j8Sw7c1hTAbCnsmKEfyrV18Q==,iv:pIni+BZcVCiiW9nfTbG/UtAz7NONX9VbCdHapJkB/B8=,tag:LK+gCLDpIes//lX5BqUKYg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUHordXp5anlUc3ltM3pJ
        QlIyZGJRSWxiMUNWeFJzZU5XNS9FYUFjUUFZCkhaa1NOQ1JzeG1xY3d3L2Iyb0I0
        aVd1RUF6d29QOWJFRmsyNThhU2JZa0UKLS0tIEx5V2MzQTk2ZmkxczllTGMyeHRH
        aU1hYW9ZQzE2RFcyZEdOeWUzWlYzUGsK22ZKgbunaZyMpRvr+iMbn3oAJkOTGuqy
        34zMt0RkB+hV0SjWXKcOVyPTPbYb84Jzf5/xj+wizmsTAU7SQrzxKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:05:59Z"
  mac: ENC[AES256_GCM,data:Ho389aGjN5T4Jmld2atP0CoSM8Aub+6yJlTxPJv8lz8JlPghI1tuK38WfshCe98o73NxRtxrCRwjOzWs/w7YO7P66O4bzgqCD+N9qjoJU+MvuGoh98djeELbQNsm+XupmtO4ippS7dPFUEL+iA7Nkiomy68CPCMLCEfGLt2r7Fo=,iv:Y9tFNu7x2rf8YQ/ONCYJFojTHFE0FULmYiA2QibWTNE=,tag:+0Lv5rpzfP9fYUAb1ntNNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
