# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uLnTlFzs+BOQc3xneu93WmJIa+12nV7v7yyOnT6s2f5dz6/sYeo71w==,iv:L5ED4OmBRyVxU+lNcMGON7qkZiexdI0CYjX5npi2RvQ=,tag:jJKnwHY0HsbwyGLo7v2NVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVmoyQWNsY1R1L3ptSTFV
        ZmRaNmw4OTJOUHpab3BoTHhYZkI0SWhHOEJBCjhMeG9BTGFWK3IrbjlPU0o4d2Nn
        Yjl3WUhMbStPVSt0S2VQTDhTSHd3Z3cKLS0tIHVCenQvdU1GU05IQUltTnBrc0pX
        NE1mKzJLNmp2SnZXdEtWNUVJZ1NlOTAKQ6+nWGhRAUAqHJccoh4rCrMZnqrGcJsL
        GX44t6VJLygb7NyPxHbjt0xG+B6PCwXqEMX0VxTMyWxGo0QrmnJO8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:08:31Z"
  mac: ENC[AES256_GCM,data:F4WkmP/gVYsR/km4eKJbxHcENYjkWcgcSMAc6XRV60RQi4p1Tv52dNOdCN2vlICZTXDPvrU9OquDGIJkiRacS5RWE0m2TAt9bWj5kXpwfYpqtb3KrrCw1V3rzpR0jBPI7RKoXHbevqGeJcV0B9ULEkYL2XlsZW8djEMOqqIvjzE=,iv:YNTkt4hknONjxeEzTGj+gMxB8GaTAdqNNZB3DoHLJoo=,tag:ypVn91IctL+52oq26g/LAg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
