# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gUvxZCc6cB0mO9LjMjByftpOod5gR4/Rm+Lzb8p+MSB+3/9V,iv:tHL401cSsPQypuRdVqm077EZvBH/0ik+QLkLoV5biQ4=,tag:vgA3gh0cuVbY6Aei4rIFyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzejE5QlBua0hEaWZ5a29k
        cGpQVFhrZVFodXVnQzNCYU8vcE94Z0lQd0JrCnY0TDBCdUIyeit3V2JSSWxKUWxW
        VHk1dHltK2oxVDNpbDE1V2dHVTlvS2cKLS0tIDRBOGRoaGFEYnRhcVhzdFcxWEJu
        WGFPd1hMQTFvekFZc0IrYWVFUDdjR1UKJuQft0tmly8hO2R2BXCyUKccEZhoLTy/
        j3tvkKGeuiyxM+5cWcbASHav8psceli8U5RFuw4qoUhCXfC0nRJgOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T20:48:33Z"
  mac: ENC[AES256_GCM,data:d9Tg2ZNJSMfSwZK8G/iR0dEbm4hgEnjOCcsEQscwFdd8TQCB5peORSheurG6060KNOmuTT8+4BAP+Mx8412AxC6zGUauYLi1348ew2VQDihJ5EWhQ/aR4eqLIoB95dgDL2QjCdPbIFufo4WbiESE5/o+bgUHtMvz6RxrHI2b3b0=,iv:W4MsH2Qj5XhHxXbR+sapuTji8lni+srW8OAOG7qXYPI=,tag:PcWirkAbJne7ywb6Kvld+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
