---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &apppg cloudnative-pg
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/cloudnative-pg/app
  postBuild:
    substitute:
      APP: *apppg
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: cloudnative-pg
      namespace: database
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appcluster cloudnative-pg-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudnative-pg
  #   - name: openebs
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  postBuild:
    substitute:
      APP: *appcluster
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
