apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
  namespace: network
spec:
  hostname: k8s-subnet-router
  proxyClass: tailscale
  subnetRouter:
    advertiseRoutes:
      - 192.168.86.0/24
      - 10.0.10.0/24
      - 10.0.90.0/24
