apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:pix0LMEvMxIyHSJLG8L5t1TQOMkJW6irZpjZcAuh2IkcHUzh6qkwvnRU+rNbNT9BhqRRDWOnFey5uDk31qwQhPdZKGqrRtUFIJfzVQmSMdOmCYTB5x8fHAcynCmFAp9Ix9iOLAe17Spx3mS/J9WApvLR1Sv4twJ6ew==,iv:7+k5jouNqd3T+Ig7TL3Ocq/v9fPdHKjENb3MsXR9TQY=,tag:W594leb12I45/dA60T3beA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOTFQZVpmWG42UCthVHRH
        UlYzYUNhK25LQ0FzalNubHh6Q1IzMUJSbWlJCmZHMTF2U1FhRGRiQ0M2cis2ZXI5
        bXB1TlpGY00zRFBlMHFmRHJDSGYrZ0kKLS0tIEJpY3VMbGw3NldIYkpEdkRrVm1O
        NHVZUTRacXhyTjRicXJlTXdSN2dLcmcKBvi3D933PpxpnJgwPcR8xN9dAhW5scwI
        VoLTi4Dnhk3HexNseO0z2WDUd3VHt4lkuY5sAvVlo6yqU/0fDsgcpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T22:04:21Z"
  mac: ENC[AES256_GCM,data:f7j2orE8mykIaxsmWVwsHDzK5L57JmN3OYmLBz0GQQAkH/JrKAw5HeIeV/SAmVadyfRBPz/D4dvbYlhBEn1L0l5Hm4PEcF0G7JtI3TTa05OivyDe70I238sbXLMTb06Cf+fzKl9hiS8O1ahdBXEEV+yohwZsm67JgpxFwoX0nvc=,iv:1kCRhmc2GAKIREMGVT35sI27Dx5v5jFRf+2B5dQ9gas=,tag:tI9laG5x5bdgDBo96dLDpw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
