---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configMapGenerator:
  - name: pgadmin-configmap
    files:
      - servers.json=./resources/servers.json
labels:
  - pairs:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/instance: pgadmin
