---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cross-seed
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      cross-seed:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.12.4@sha256:9fa95ea5f350609be385edc02fbdd7a2ac8a894e02d521fb01af42e25695d7e7
            env:
              TZ: America/New_York
            args: ["daemon"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: cross-seed
        ports:
          http:
            port: 80
    # persistence:
    #   config:
    #     type: emptyDir
    #   secret-file:
    #     type: secret
    #     name: cross-seed-secret
    #     globalMounts:
    #       - path: /config/config.js
    #         subPath: config.js
    #         readOnly: true
    #   qbittorrent:
    #     existingClaim: *app #qbittorrent
    #     globalMounts:
    #       - path: /qbittorrent/qBittorrent/BT_backup
    #         subPath: qBittorrent/BT_backup
    #         readOnly: true
    persistence:
      config:
        existingClaim: *app
      config-cross-seeds:
        type: emptyDir
        globalMounts:
          - path: /config/cross-seeds
      secret-file:
        type: secret
        name: cross-seed-secret
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true
      media:
        type: nfs
        server: ${NAS_IP}
        path: /mnt/datastore/mediacentre
        globalMounts:
          - path: /Media
