apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:eL03s+8f6vTsUb+KqEH3tWQqIDh9TBcrGqsI834vJm0MYLa7Sq6i96tTp9oOUxTyJowrY0hAg7TjsG3ASco0Zh8ylcPzTjwA9V+nquV6J2yc4Bk=,iv:c4ApGM3HAWQIYr2a3jrFAivagZoQHH+PUN4KZ+4u9Ng=,tag:j4F8isdT8TwxRHsN1ex62g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:+gE/l621O5pLY5QG,iv:zksdxZ1dp4+6Fh9nRbYkLQaNMSK6pxvz4oDhKoiCiL4=,tag:WtjzNDwuz4bIe8hre7zZ5g==,type:str]
  R2_ACCOUNT_ID: ENC[AES256_GCM,data:bMO0koQqeXoGk07t1Pdbi5PJkl6dL/J2BFK3I5cbb/IF128V,iv:t0cbjdGnN6LOjYslxobHMZD7/qaopu8eYtUTTnMayEk=,tag:JTYMTd4wHJJC1w6Jw/pDGA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VqAouDvFSczrrfVvMWYrvMPAB1XqaRp719F2zS9BU5U=,iv:/7LgPJWBWKxxg75EUBEytyNeDXQarFjALMWJuPSVPtE=,tag:5zbPyVTu4D2PeJADhxkb/w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KuZ7WM8ngqDauLvOfr/r5VsJCjMbREV2qspAnwJaGAftp8FUvxcIzucW0311Asv454BE5eE8Gm8iMuju8bQEZQ==,iv:fmnwg0J/r7zFtr8yxHeYanOoGjqwlGOjmIuSTekfhmk=,tag:5TBzenSArix5Ew/oIAcPOg==,type:str]
  r2_Token_value: ENC[AES256_GCM,data:iXbKE8a4S1vXNZAk3L+g1qj+c33jUYr/+EmblUJwtwlm5Z40KwpneA==,iv:weQoO28gcXKLoBuzJ+1CrSr94mStWPEkpZUyDubPFrc=,tag:fITGbxttDX7pokjhWBqH9A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YzBhUFFuUnQ0K2F2UnVn
        elkxdkJjaGxJbEpNSU4vMnBpL1NZR2ROQjNNClEyREVxVDAwZ3doUC9ZLzhEcDBx
        dTkyZjE5QkRpdkszRDgyRE9lVXNYZFEKLS0tIEZ4eGdJNkNnTzl5QlE1RE5tRHMv
        ZnRmclFNdUEvT3lnZVBSUmhzYVEzdzQKRv3YF8jLZKL1qCYCvw3uG12mK/9LNGRk
        oKoG3XS8GEYrtRBTFROIB4GsmTz2XtUPsebeZGs68m/1eugDrfrkSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T20:54:59Z"
  mac: ENC[AES256_GCM,data:LlXcNsaRoVJqqGDvd3VUCqYdyIFLae5lnXIPlCwRuFUEuvSgkCReZUqJyDvjPELV9sS2a6OKhaa6uz6GaAScZtVMmXem/6YgfYBeM8SHy6uP5y489rLH2L/Erus4G9cy+QtAVPzgyJt77SoCjRLgtDtcAsbKeujDfbOugJCjPAE=,iv:DlhlHfnIsj99QAV7rFBDaGWlMjOgw+FRXZ8WwIEt7tM=,tag:/hJo+a4bXZewP7+8OWJtog==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
