apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:MKCB958Z4qQ3bZjwLss5KumiborsjpbwgtJ1T1fSAuJXoESLHTLXDi+B3alrLMv2gDAXSYRUP57Sv4uVw7kU+uRP1q7oDWp36zRfKGbAIS8xOWs=,iv:K1jy+JDDvbPz2Al0dSVcSf59hb6SfH0XCVgq0PHc9e8=,tag:hKK/svS+Xeia4vb76gpjKw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:5vJXlDc2chbjq0mF,iv:JGB5xVmdivwn6QoZPeQUdOnsKXrOfdQR2nwX8/HHRwA=,tag:my+ywP5iE6j3KpILidwOvg==,type:str]
  R2_ACCOUNT_ID: ENC[AES256_GCM,data:vDOYY3d8dBTwnGtXmcpCCWNJTSY3IEdIM2oWkCtXbfGdNr+8,iv:OSweWStM+nqA3naUNu5L5scKymD5X3aEQvdubcZ9kiE=,tag:HAscu1wgv4xI86GyXqxqMA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nxzSSvSFGv0ye9fp1IRQWsvSVt+/isOMr1vbqIzdZzM=,iv:SoZKy/n6FFtNunscq4KiKdZs9sLCVZoCylkEf+np/mw=,tag:Lu8fWkv5NAmSo3UQynXsCQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dPOjK+F+SyccSe/8fjNX5/f10gHffRQgDqVqK4kNRXFLg0CWljb+zDz17W/4ht1iOsDIgGOI30VCATXLGJOXOA==,iv:Nsx/Mdp5WvgGERKnatw//R7BJdE3c5ZVgBJFkUtS3v4=,tag:8tOfFa963bge/LqzUjM+DQ==,type:str]
  r2_Token_value: ENC[AES256_GCM,data:bXLJyd3yWDMjbwhlCYCl3claQJF/OzZVTcP0iwyHFUARBOPUJ43rzg==,iv:osc+UyiZyOt1bTFziJCeFtNQTkl1QijW7tf9zjC5SxE=,tag:Lqn8s6HWIYYPrspsH1Y7Iw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2J5eEw4VTZuWnVTY2s2
        SEFyT1RZYTlWSnZuRytackVuRTNadXpRNjFvCk1mNjI1d0N3dlM3YXp6MVp2cUxW
        NWZKS1VzcStvZzJ6OWNnUXBrcjhya0UKLS0tIHNVSXIwQnJtWURuQmo1TVZDTkUx
        N29CM21GSHVzb0ZnSy9QZEtkaHJqV1EKsBXfbIWophERRhqUsAaRK+UIdeqTW4bJ
        7p+gbZ+RbDZvSmvsZA964mZIF1JCSg3Dq01T43yU3FnOk6oxEYERuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T22:47:09Z"
  mac: ENC[AES256_GCM,data:NFdyz7wJa9UBfYF/CxDRny+BLJbC2S16kopw6u+o0hATC7jFeZhP6DYm7FTfNZo/geLiZdnt2dGRdD7w8j6pryqKe4RWQKGReh2XTuabaqr8JCJ7OjIRLi9BkGccKszo5qm2jlntOnoxe1LpmW36wF2NsZN/Cs8Uloadeo8f3kY=,iv:RPkhnwJoHhVkbFaifL6CYuQOhHkon5azehGie4p8J90=,tag:HDeJF5YKl6gmEGyZSQgnPg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
