---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  target:
    name: hoarder-secret
    template:
      data:
        # AI
        OLLAMA_BASE_URL: "{{ .OLMA_BASE_URL }}"
        INFERENCE_IMAGE_MODEL: "{{ .OLMA_IMG_MODEL }}"
        INFERENCE_TEXT_MODEL: "{{ .OLMA_GEN_MODEL }}"
        EMBEDDING_TEXT_MODEL: "{{ .OLMA_EMB_MODEL }}"
        # oidc
        OAUTH_CLIENT_ID: "{{ .HDR_AK_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .HDR_AK_CLIENT_SECRET }}"
        NEXTAUTH_SECRET: "{{ .HDR_ENC_KEY }}"
        MEILI_MASTER_KEY: "{{ .HDR_MEILI_KEY }}"
  dataFrom:
    - extract:
        key: hoarder
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: ollama
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
