---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.24.1

            env:
              BROWSER_WEB_URL: http://hoarder-chrome.selfhosted.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data

              DISABLE_SIGNUPS: false
              DISABLE_PASSWORD_AUTH: true

              OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true
              MEILI_ADDR: http://hoarder-meilisearch.selfhosted.svc.cluster.local:7700
              NEXTAUTH_URL: https://hoarder.${SECRET_DOMAIN}
              # Ai
              INFERENCE_JOB_TIMEOUT_SEC: 600 # 10 Minutes
              OLLAMA_KEEP_ALIVE: 2m
              # oauth
              OAUTH_WELLKNOWN_URL: https://sso.${SECRET_DOMAIN}/application/o/hoarder/.well-known/openid-configuration
              OAUTH_PROVIDER_NAME: authentik

              DISABLE_NEW_RELEASE_CHECK: true

              # https://github.com/nodejs/corepack/issues/612
              COREPACK_INTEGRITY_KEYS: 0

            envFrom: &envFrom
              - secretRef:
                  name: hoarder-secret

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2G

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1G

      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - hoarder
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.14.0
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: true

            envFrom: *envFrom

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 8G

    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Bookmark manager
          gethomepage.dev/group: apps
          gethomepage.dev/icon: sh-hoarder.svg
          gethomepage.dev/name: Hoarder
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: hoarder-data
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder

          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
