---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app lubelog
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-cluster
      namespace: storage
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: storage
  components:
    - ../../../../components/volsync
  interval: 30m
  path: ./kubernetes/apps/selfhosted/lubelog/app
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1003"
      APP_GID: "100"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
