# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DplUDRP+9ElkjWQUpaE2itqVYTxHq8AQO1j6cs0RKIc=,iv:stnjm+004wotdAID+vJawGofgDHid/S/tP+RvMkSv1Q=,tag:WF8AoI1BvZDYoHTfub4/Wg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14rs0f3fjjydjc9p34nhkekc4h8g9pwaw7xdzqmks04s60cnzmetqflrc68
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQnRISFdsY1Q1T2tSM2FZ
        dU05WjFlc1JHS1V5Tzc5cFNIVTdOYStMckJzCjNFVHpwaGYvNTh3bnJWRFd5QU5i
        NHNyVCtHeCsxNDlObGU4R2VNYUUweVUKLS0tIFBmYTF1SjNBVUNrUGlUTGhBWCtt
        b1BlcFlPb0szUWtieU9NbUhOQkI1c3cKr4M6Ogs6ctiharPPzky1KHTfwJDGAicM
        SyPBtUvx2bAhlUSVx414tsz7O7jW7DfzJiEr2lzZro09V5zummNY5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:08:31Z"
  mac: ENC[AES256_GCM,data:/z8TQZftnuFoRqK+Z5ORd7wuzltkvQ/6URfL/yhOUwfu32rgQnd11dTu8kL8QUvTMjay5QkcYvqxrE530NMSb/bYymEoPNOXgGxbnyWqI9lYdOUJURtmUezaFtj4Xd6vZ3ApVhYm9GST3L0GqHPrn9mwZ666UZSaaRrBUUn/dHY=,iv:+AUDqxfmyJ/dTG6lITWNHatnNykqH/XEBHeDXaqrRDQ=,tag:kusk/P1vgbbq5ZNLp8KOEw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
