---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.82.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    operatorConfig:
      hostname: "tailscale-operator"
      defaultTags:
        - "tag:k8s-operator"
      extraArgs:
        - "--advertise-exit-node"
        - "--advertise-routes=0.0.0.0/0"
    apiServerProxyConfig:
      mode: "true"
