---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: default
spec:
  interval: 6h
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: flux-system
  values:
    global:
      logLevel: "INFO"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
          ephemeral-storage: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
          ephemeral-storage: "256Mi"
    newtInstances:
      - name: "main-tunnel"
        allowGlobalOverride: false
        auth:
          existingSecretName: "" # Keep empty for inline credentials
          keys:
            endpointKey: "PANGOLIN_ENDPOINT" # These should be key names
            idKey: "NEWT_ID"
            secretKey: "NEWT_SECRET"
        # Put the actual values here:
        pangolinEndpoint: "https://pangolin.hayani.xyz"
        id: "o1dmghwxl799mca" # Your actual ID goes here
        secret: "256t2np06yomo9h3vxrm41djk8gdtlk1op08ai2ptlco6sly" # Your actual secret goes here
        healthFile: "/tmp/healthy"
        logLevel: "INFO"
        mtu: 1280
        acceptClients: false
        useNativeInterface: false
        interface: "newt"
        service:
          enabled: true
          type: LoadBalancer
          port: 51820
          testerPort: 51821
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
