---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: default
spec:
  interval: 6h
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: flux-system
  values: # <-- All your configuration should be under 'values'
    global: # <-- Move this under 'values'
      logLevel: "INFO"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
          ephemeral-storage: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
          ephemeral-storage: "256Mi"
    newtInstances: # <-- This should also be under 'values'
      - name: "main-tunnel"
        allowGlobalOverride: false
        auth:
          existingSecretName: ""
          keys:
            endpointKey: ""
            idKey: "o1dmghwxl799mca"
            secretKey: "256t2np06yomo9h3vxrm41djk8gdtlk1op08ai2ptlco6sly"
        pangolinEndpoint: "https://pangolin.hayani.xyz"
        id: ""
        secret: ""
        healthFile: "/tmp/healthy"
        logLevel: "INFO"
        mtu: 1280
        dns: ""
        pingInterval: ""
        pingTimeout: ""
        acceptClients: false
        useNativeInterface: false
        interface: "newt"
        keepInterface: false
        configFile: ""
        generateAndSaveKeyTo: ""
        dockerSocket:
          enabled: false
          path: "/var/run/docker.sock"
          enforceNetworkValidation: false
        mtls:
          enabled: false
          secretName: ""
          certPath: "/certs/client.p12"
          p12Base64: ""
        updown:
          enabled: false
          script: ""
          mountPath: "/opt/newt/updown"
          fileName: "updown.sh"
        podSecurityContext: {}
        securityContext: {}
        service:
          enabled: true
          type: LoadBalancer
          port: 51820
          testerPort: 51821
          externalTrafficPolicy: ""
          loadBalancerIP: ""
          loadBalancerClass: ""
          loadBalancerSourceRanges: []
          nodePorts:
            wg: ""
            tester: ""
          annotations: {}
          labels: {}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        nodeSelector: {}
        tolerations: []
        affinity: {}
        extraEnv: {}
        extraVolumes: []
        extraVolumeMounts: []
        initContainers: []
        extraContainers: []
        useCommandArgs: false
        hostNetwork: false
        hostPID: false

        #
