---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENC_KEY }}"
        N8N_USER_MANAGEMENT_JWT_SECRET: "{{ .N8N_JWT }}"

        DB_POSTGRESDB_DATABASE: '{{ index . "dbname" }}'
        DB_POSTGRESDB_HOST: '{{ index . "pgbouncer-host" }}'
        DB_POSTGRESDB_PORT: '{{ index . "pgbouncer-port" }}'
        DB_POSTGRESDB_USER: '{{ index . "user" }}'
        DB_POSTGRESDB_PASSWORD: '{{ index . "password" }}'

        N8N_EXTERNAL_STORAGE_S3_HOST: "http://{{ .MINIO_ENDPOINT }}:{{ .MINIO_PORT }}"
        N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME: "{{ .MINIO_BUCKET }}"
        N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION: "{{ .MINIO_S3_REGION }}"
        N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: "{{ .MINIO_SECRET_KEY }}"

        N8N_SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        N8N_SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        N8N_SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        N8N_SMTP_PASS: "{{ .EXTERNAL_SMTP_PASS }}"
        N8N_SMTP_SENDER: "{{ .N8N_EMAIL_SENDER }}"
        N8N_SMTP_SSL: "{{ .EXTERNAL_SMTP_SSL }}"
        N8N_SMTP_STARTTLS: "{{ .EXTERNAL_SMTP_STARTTLS }}"
  dataFrom:
    - extract:
        key: n8n
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: n8n-tfm-minio
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: minio
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: external-smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-n8n
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
