apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app portainer
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/default/portainer/app
  dependsOn:
    - name: haproxy
      namespace: rook-ceph-external
    - name: volsync
      namespace: storage
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/guarded
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 129Mi
      VOLSYNC_START_MINUTE: "11"
      VOLSYNC_CACHE_CAPACITY: "1Gi"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
