---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  target:
    name: lldap-secret
    template:
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_USER_ADMIN_PASS }}"
        LLDAP_LDAP_BASE_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_USER_ADMIN_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
  dataFrom:
    - extract:
        key: lldap
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  target:
    name: lldap-db-secret
    template:
      data:
        LLDAP_DATABASE_URL: 'postgres://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" }}/{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-lldap
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
