---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      lldap:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &dbsecret lldap-db-secret
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.1@sha256:4931eeeb841b1bbf5774161b5fd9dab88f41ffeb4b08ca656f0b7595cd7cb52a
            env:
              TZ: ${TIMEZONE}
              LLDAP_HTTP_PORT: &webport 17170
              LLDAP_HTTP_URL: https://lldap.${SECRET_DOMAIN}
              LLDAP_LDAP_PORT: &ldapPort 389
            envFrom:
              - secretRef:
                  name: lldap-secret
              - secretRef:
                  name: *dbsecret
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: *app
        ports:
          web:
            port: *webport
          ldap:
            enabled: true
            port: *ldapPort
    ingress:
      app:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:account-multiple
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: lldap
          gethomepage.dev/description: Light LDAP implementation
          gethomepage.dev/group: infra
          gethomepage.dev/icon: sh-valkey.svg
          gethomepage.dev/pod-selector: >-
            app in (
              lldap
            )
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: web
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
