---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  target:
    name: mealie-secret
    template:
      data:
        # AI
        OPENAI_BASE_URL: "{{ .OLMA_BASE_URL }}/v1"
        OPENAI_API_KEY: "{{ .OLMA_API_KEY }}"
        OPENAI_MODEL: "{{ .OLMA_GEN_MODEL }}"
        # OIDC
        OIDC_PROVIDER_NAME: authentik
        OIDC_CLIENT_ID: "{{ .MEAL_AK_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEAL_AK_CLIENT_SECRET }}"
        OIDC_ADMIN_GROUP: "authentik superusers"
        # Database
        POSTGRES_SERVER: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_USER: "{{ .user }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "{{ .dbname }}"
        # email
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        SMTP_USER: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        SMTP_FROM_EMAIL: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
  dataFrom:
    - extract:
        key: mealie
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: ollama
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: external-smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-mealie
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
