---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.8.0
              pullPolicy: IfNotPresent

            env:
              TZ: ${TIMEZONE}
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              DB_ENGINE: postgres

              PUID: &uid 1000
              PGID: &gid 1000

              API_PORT: &port 9000

              SMTP_FROM_NAME: "Mealie"

              OIDC_AUTH_ENABLED: true
              OIDC_CONFIGURATION_URL: "https://sso.${SECRET_DOMAIN}/application/o/mealie/.well-known/openid-configuration"
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: apps
          gethomepage.dev/name: mealie
          gethomepage.dev/icon: sh-mealie.svg
        hosts:
          - host: &host mealie.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data

    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 200m
        memory: 800Mi
